name: Reyskaw
favicon: null
layout_spectrum: 0.7053545559756458
typography_spectrum: 0.10460366192273796
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5341848717071116
  lightness: 0.09459642576985061
  saturation: 0.5780162333976477
  rhythmicContrast: 0.8739089956507087
purpose: []
